### ISSUE TITLE
Logo proposal (with samples)

### ISSUE THREAD

**Issue by f1yn** [stasm/innerself#14]
The growth of this repository has been amazing since the last couple of days. In light of this, I feel like it would be great to add a logo to **innerself**

While creating these samples, I tried to keep the repository's goals in mind. I also tried to keep it simple as I could.

* Lightweight and minimal (just like the library)
* Without words (since **innerself** is a library, not a brand)
* Without distractions (I tried to design it like a flag symbol [(Principles of Flag Design)](https://www.youtube.com/watch?v=tENhOnfD82M) [(TED - Roman Mars)](https://www.ted.com/talks/roman_mars_why_city_flags_may_be_the_worst_designed_thing_you_ve_never_noticed))

Here are the samples I came up with, in four different variations. The brackets represent the inner part of HTML, and the two dashes represents the value, a reference to `elem.innerHTML =`.
https://imgur.com/f5WFraR **(EDIT: see examples below)**

I chose the colors because I like them, but I am more than willing to experiment with different schemes if you'd like.

Once one is picked, I can begin making a more production quality version of it (a light version, and another with a white outline to add contrast on dark backgrounds).

These were made using Inkscape on Linux, the render was made using GIMP.

**Comment by f1yn** [comment]
Once one is picked, I'd be more than happy to embed it into the README with a PR.

**Comment by michalbe** [comment]
@flynnham Maybe it would be easier if you put each proposal in a separate comment, and then community will vote with emojis?

**Comment by stasm** [comment]
@flynnham Thanks for starting the discussion and for submitting the first proposals!

I appreciate the research and the goals that you outlined. I'm a huge Roman Mars fan myself! (I listen to _99% Invisible_ on a weekly basis.) Defining the goals helps to make the discussion more objective. I'd explicitly add a goal of not using custom shapes, just like _innerself_ doesn't use a custom solution for Virtual DOM diffing. Your proposals already only use the equals sign and the angle brackets, so it looks like we're already on the same page!

In the end, however, it always boils down to aesthetics. For me, "lightweight and minimal" would mean going for a black square (which I'd like, too!) :) I'm not a designer myself by I grew up with my both parents being industrial designers and if there's one thing that I learned from them about art and design is that design doesn't lend itself well to the democratic voting process.

To keep faithful to the minimalist nature of the project, I'd suggest only using black and white for colors and limiting the logo to two shapes at the most. And since one of the main principles of _innerself_ is to use as much of the browser's native features as possible, how about we choose a Unicode symbol? It would allow anyone to _type_ the logo on their keyboard, without having to resort to using images!

Here are a few suggestions from me to get the discussion going. I linked the individual characters to their pages in the Unicode tables. GitHub shows them in blue, but in the logo they would be black.

  - "Minimalist": [■](http://shapecatcher.com/unicode/info/9632), [⚫](http://shapecatcher.com/unicode/info/9899), [◌](http://shapecatcher.com/unicode/info/9676),
  - "Composable": [❖](http://shapecatcher.com/unicode/info/100700), [❑](http://shapecatcher.com/unicode/info/10065), [⧉](http://shapecatcher.com/unicode/info/10697)
  - "Inner": [◘](http://shapecatcher.com/unicode/info/9688), [◙](http://shapecatcher.com/unicode/info/9689), [◉](http://shapecatcher.com/unicode/info/9673), [◈](http://shapecatcher.com/unicode/info/9672), [⦿](http://shapecatcher.com/unicode/info/10687), [⚈](http://shapecatcher.com/unicode/info/9864)

**Comment by f1yn** [comment]
I'll come up with some more concepts later today.

**Comment by stasm** [comment]
Here's a shortlist of the five Unicode symbols that I like the most, presented alongside the wordmark.

### ■ innerself
### ◘ innerself
### ◉ innerself
### ⚈ innerself
### ⧉ innerself

**Comment by f1yn** [comment]
## Concept mA:
![p1](https://user-images.githubusercontent.com/6565187/30287626-c6ee978a-96f3-11e7-9b4b-8955b4950f8d.png)

**Comment by f1yn** [comment]
## Concept mB:
![p2](https://user-images.githubusercontent.com/6565187/30287649-dbd5ac7e-96f3-11e7-91a3-bd7426d0f538.png)

**Comment by f1yn** [comment]
## Concept mC:
![p3](https://user-images.githubusercontent.com/6565187/30287662-ef74341c-96f3-11e7-8882-98f7a4ba619d.png)

**Comment by flynnham** [comment]
## Concept mD:
![p4](https://user-images.githubusercontent.com/6565187/30287669-f86498b4-96f3-11e7-916d-8b87933def4f.png)

**Comment by flynnham** [comment]
### Concept mD-1 (with minimal contrast):
![p5](https://user-images.githubusercontent.com/6565187/30287693-117d9bde-96f4-11e7-9a05-bf5cba1333cf.png)

**Comment by f1yn** [comment]
## Concept mC-1:
![mc-1](https://user-images.githubusercontent.com/6565187/30288081-7c4dd9e6-96f5-11e7-911d-d6d001202127.png)

**Comment by f1yn** [comment]
## Concept mD:
![md](https://user-images.githubusercontent.com/6565187/30288099-8ee1502e-96f5-11e7-8261-a590334ca46f.png)

**Comment by f1yn** [comment]
## Concept mD-1:
![md-1](https://user-images.githubusercontent.com/6565187/30288124-98facf0e-96f5-11e7-81ec-815997e578d9.png)

**Comment by flynnham** [comment]
Personally, I am more partial to having a at least two tone, mono-chromatic icon. I think something like this (strangely enough), adds at depth and life to it:
# Concept mD (with contrast)
![md-contrast](https://user-images.githubusercontent.com/6565187/30288171-c8d9afe2-96f5-11e7-8872-c3803e9112d0.png)

**Comment by flynnham** [comment]
@stasm That fifth icon does not appear for me.

**Comment by f1yn** [comment]
## Concept sA
![sa](https://user-images.githubusercontent.com/6565187/30291603-684d6f5e-9701-11e7-8a8c-5423d8b82dc0.png)

**Comment by f1yn** [comment]
## Concept sA-1
![sa-1](https://user-images.githubusercontent.com/6565187/30291618-73e4d30c-9701-11e7-8cc9-b86a931131f4.png)

**Comment by f1yn** [comment]
## Concept sB
![sb](https://user-images.githubusercontent.com/6565187/30291643-88bd0fd8-9701-11e7-9cf2-a1152d3437c9.png)

**Comment by f1yn** [comment]
## Concept sB-2
![sb-2](https://user-images.githubusercontent.com/6565187/30291654-93c1ca54-9701-11e7-895b-77450bc50be4.png)

**Comment by f1yn** [comment]
## Concept sC:
![sc](https://user-images.githubusercontent.com/6565187/30291825-09b5b52c-9702-11e7-8edd-8a6a714d8125.png)


Similar unicode: ◈ *innerself*

**Comment by f1yn** [comment]
## Concept sC-1:
![sc-1](https://user-images.githubusercontent.com/6565187/30291964-73a56c2a-9702-11e7-97fc-499d0d91958a.png)

**Comment by f1yn** [comment]
## My personal choice (sD): 
![mychoice](https://user-images.githubusercontent.com/6565187/30293069-48dbec68-9706-11e7-8c72-c6e580d987c4.png)

This one is my favorite, mainly due to the fact it has meaning. it's simple, minimal, can be mimicked by the unicode symbol ◈, but also contains a reference to the XML tags of HTML.

**Comment by stasm** [comment]
@flynnham Thanks for putting these together! This is exactly what I meant :) It might be worth seeing how these proposal work under different sizes. Do you perhaps have a SVG that I could play with?

The last character from my previous comment was this one: http://shapecatcher.com/unicode/info/10697.

**Comment by f1yn** [comment]
@stasm Do you want all of the SVG or just some? I can create a PR containing the files, or send them some other means.

You could PM me on Twitter if you'd rather I send a zip file. 
* * *
Just a forewarning, some of these SVGs arent super optimized. That shouldn't really be an issue for now, mainly because people would be more likely to use the rasters anyways.

Plus, an SVG can easily be optimized with the right software. Unfortunately, all of the SVG optimizers I've tried with Inkscape-made SVG seem to do terrible things with the images.

**Comment by ben-styling** [comment]
Personally I think solid black isn't aesthetically pleasing, but I do understand why it could be argued that it's a good idea for this particular logo. I'd suggest something like `#262525`. Very close to black, but not quite as jarring.

Once a logo is chosen I'd be happy to optimise the SVGs.

Here is (sD). 
First version is two paths, where the white part is defined as white, the second is one path where the white part is cut out of the black.

```
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32">
<path id="background" d="M32,16L16,32L0,16L16,0L32,16z"/>
<path id="foreground" fill="#FFFFFF" d="M14.8,23.4v3.5L3.9,16L14.8,5.1v3.5L7.3,16L14.8,23.4z M24.7,16l-7.4,7.4v3.5L28.1,16L17.2,5.1v3.5L24.7,16z"/>
</svg>

```


```
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32">
<path d="M16,0L0,16l16,16l16-16L16,0z M14.8,8.6L7.3,16l7.4,7.4v3.5L3.9,16L14.8,5.1V8.6z M17.2,23.4l7.4-7.4l-7.4-7.4V5.1L28.1,16 L17.2,26.9V23.4z"/>
</svg>
```

**Comment by stasm** [comment]
> Personally I think solid black isn't aesthetically pleasing, but I do understand why it could be argued that it's a good idea for this particular logo. I'd suggest something like #262525. Very close to black, but not quite as jarring.

Great point, I agree!

**Comment by stasm** [comment]
I keep coming back to this Unicode character ⧉.  I like that it's just two squares. It's super simple, and yet it implies composability and architecture. If you tilt your head a little bit to the side, it also sports two angle brackets `<>` :)

![squares](https://user-images.githubusercontent.com/265818/30388891-7e5ac4ca-98b1-11e7-8ef8-6d461b3ff054.png)

Would someone like to give this character a try with their design skills?

**Comment by f1yn** [comment]
@stasm Once I get home I'll make a couple iterations of it for you.

**Comment by f1yn** [comment]
@stasm Alright, so there is an issue. At least on Android (using either Firefox or Chrome on Nougat), the character for the above symbol does not render. [Here are the screenshots on Imgur](https://imgur.com/a/iAZGd)

To summarize for the busy: it's rendering as plain blocks and not as the symbol. I'm personally not sure that logo will be the best choice for mobile. I'm not exactly if this is font-based or not, I'm going to assume that Android does not natively support the symbol.

EDIT: Yeah, in the multiple areas I've tested it (notes apps, online text fields of various sites) it just shows a blank box on both browsers.

**Comment by stasm** [comment]
I've been thinking about this for the past few days. There's something about the __sD__ concept that doesn't resonate with me. All of this entirely subjective: the diamond shape feels rigid and there's just too much going on with the two angle brackets inside of it. It feels like it takes us away from the principle of minimalism.

Out of the proposals above, the one that I'm most fond of is __sB-2__: ◘. I think it embodies what _innerself_ strives to be. Two simple shapes stripped down to the bare minimum with two basic colors complementing each other. No frills, no excess. Both shapes work together to create the whole—that's _composition_—and the circle is inside of the larger box which brings the _inner_ part to mind.

Judging by the emojis in this issue, other people here didn't feel the same way about sB-2. In light of this I'm not quite sure how to move forward. @flynnham do you have any suggestions? :)

**Comment by f1yn** [comment]
I think the important thing to consider is that regardless of the logo picked, it can change as the project grows. I'm caught too, because I feel like the development community has a bias towards more complex and distinguishable logos, which is exactly what I was approaching with my original concept as well as the **sD** concept.

That being said, you are pretty much right. I think **sB-2** is a great match, mainly because it's Unicode character is easy to read, as well as it provides good contrast when inverted. It's also not complex enough to need a white outline version (like the React and Angular logo).

***

Again these are all concepts, we can tweak them as we see fit and experiment with new concepts. Art concepts should not remain in a singular state forever. If we pick a concept, there should be nothing holding us back from updating or re-inventing the logo as we see fit. **EDIT:** The whole "I'm unique part" + my background on music was somewhat unneeded, so I ended up removing that.

**Comment by wrick17** [comment]
I vote for sB-2 as well. it's simple and fits the library theme really well. I also love a minimal theme as well.

**Comment by stasm** [comment]
@flynnham I like your approach to the iterative process here :) Would it be okay for you if we went for __sB-2__ for now? If the library outgrows this choice, we can revisit later.

**Comment by f1yn** [comment]
Alright, I've attached the SVG for the sB-2 concept.
[sB-2.zip (https://github.com/stasm/innerself/files/1311235/sB-2.zip)](https://github.com/stasm/innerself/files/1311235/sB-2.zip)

@GoldenRust Are you still available to do some optimizations?

**Comment by ben-styling** [comment]
@flynnham 
These are edge-to-edge so they don't have the white border included in the artboard as in your original, however if that's a requirement let me know and I'll change it to include it.

Two elements
```
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32">
<rect width="32" height="32"/>
<circle fill="#FFFFFF" cx="16" cy="16" r="7.6"/>
</svg>
```

One element
```
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32">
<path d="M0,0v32h32V0H0z M16,23.6c-4.2,0-7.6-3.4-7.6-7.6s3.4-7.6,7.6-7.6s7.6,3.4,7.6,7.6S20.2,23.6,16,23.6z"/>
</svg>
```
