### ISSUE TITLE
innerself hacker news SPA

### ISSUE THREAD

**Issue by bsouthga** [stasm/innerself#16]
(not really an issue) -- I was inspired by your project and wanted to see how it felt to build a small SPA with `innerself`, so I made a hacker news clone: https://github.com/bsouthga/innerself-hn

It actually plays really nice with typescript too.

**Comment by stasm** [comment]
I'm speechless.

**Comment by stasm** [comment]
I added a _Showcase_ section to the README in 103a3ed4b9c3eb6ced101ca732209734de2610a1. I would love it if you submitted a PR and added _innerself-hn_ to the list!

**Comment by wrick17** [comment]
Amazing work!! @stasm I feel like an optional built in router would be a great addition to this library.

**Comment by stasm** [comment]
Nice work on the routing, `combineReducers` and the `JSON.stringify` trick in one of the signatures of `dispatch`!

**Comment by stasm** [comment]
@wrick17 I agree. We now have three prototypes: yours, @bsouthga's and my own in the game I originally wrote innerself for :)  I'll try to spec something out in #9 over the weekend.

**Comment by wrick17** [comment]
@stasm Awesome!! Trust me. Those big heavy frameworks are going to be so jealous 😋

**Comment by bsouthga** [comment]
@wrick17 @stasm thanks! 

Yeah for routing I found that emulating https://github.com/FormidableLabs/redux-little-router seems to work nicely with the data flow. 

If there was to be a suggested routing pattern for innerself, I might vote to keep it as an optional plugin (to keep the minuscule footprint of the original lib) -- maybe similar to the logging plugin.

**Comment by wrick17** [comment]
@bsouthga Yes. Even I would vote for the router to be optional. That way only people who need it, import it. For others it can be just in few bytes.

**Comment by stasm** [comment]
I'm going to close this now that #17 has been merged. Once again, amazing work, @bsouthga, thanks!
