### ISSUE TITLE
Match API

### ISSUE THREAD

**Issue by damassi** [stasm/innerself#5]
I know people have their preferences in terms of code readability, but since this is sort of a replacement in situations where size is important it would be nice if the API matched Redux exactly -- e.g., `createStore` vs `create_store`, etc, sticking to the idiom.

**Comment by f1yn** [comment]
I'll create a PR for this, I'm more partial to camelCase as well.

**Comment by stasm** [comment]
Thanks for raising this. I'll admit I prefer naming conventions similar to those in Rust (`snake_case` for variables and methods, `PascalCase` for classes). I do understand the concern, however, and I think it's better to follow the rule of the least surprise. Let's do it.

**Comment by f1yn** [comment]
Proposed in this PR: https://github.com/stasm/innerself/pull/6

**Comment by stasm** [comment]
Alright, #6 has been merged. I'll release version 0.1.0 later tonight. Thanks again!
